# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "my-portfolio"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # - name: Cache node_modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{runner.OS}}-build-${{hashFiles('**/yarn.lock')}}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-${{ runner.OS }}-

      # - name: Cache Primes
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ github.workspace }}/.next/cache
      #     key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: prime-numbers
          key: ${{ runner.os }}-primes

      - name: Generate Prime Numbers
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: /generate-primes.sh -d prime-numbers

      - name: Use Prime Numbers
        run: /primes.sh -d prime-numbers

      - name: CI Setup
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          PERSONAL_TOKEN: ${{secrets.GH_PAT}}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./my-portfolio
          SCRIPT_MODE: true
